version: '3.8'

services:
  app:
    build: .
    command: >
      bash -c "python src/manage.py migrate --no-input && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: ${POSTGRES_PROD_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: ${DEBUG}
    depends_on:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_HOST: ${POSTGRES_PROD_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
